theme: jekyll-theme-midnight
title: "BARN Project"
description: "Tri 2 Project for Ben, Arnav, Riggi, and Nico."
gitorg: "https://github.com/MuffinMan1287/BARNProject"
description: "Preparation for CPT by BARN"
google_analytics:
